#!/bin/bash

[[ ${DOCKER_DEBUG} ]] && set -x

# PID, trap, wait; all belongs to 'docker stop' signal handeling.
# This is the same logic as the parent docker container, but rather this,
# than creating a one-time process in supervisord to handle this logic.
PID=; trap '[[ ${PID} ]] && kill ${PID}; exit 0' SIGTERM

[[ -f "/hooks/supervisord-pre" ]] && /hooks/supervisord-pre

/usr/bin/supervisord -n -c /etc/supervisord.conf -e ${SUPERVISORD_LOGLEVEL:-error} & PID=$!

wait
